# SPDX-License-Identifier: Apache-2.0
CONFIG_ASSERT=y
CONFIG_STACK_SENTINEL=y
CONFIG_INIT_STACKS=y
CONFIG_THREAD_NAME=y
CONFIG_LOG_MODE_IMMEDIATE=y
CONFIG_USBD_LOG_LEVEL_INF=y
CONFIG_UDC_DRIVER_LOG_LEVEL_INF=y
