CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_STDOUT_CONSOLE=y
CONFIG_UART_LINE_CTRL=y
CONFIG_GPIO=y
CONFIG_SPI=y
CONFIG_I2C=y
CONFIG_DISPLAY=y
CONFIG_INPUT=y
CONFIG_INPUT_GT911_MAX_TOUCH_POINTS=5
CONFIG_INPUT_LOG_LEVEL_INF=y
CONFIG_I2C_LOG_LEVEL_WRN=y
CONFIG_REGULATOR=y
CONFIG_MAIN_STACK_SIZE=4096
CONFIG_LOG=y
CONFIG_PRINTK=y

CONFIG_USB_DEVICE_STACK_NEXT=y
CONFIG_USBD_CDC_ACM_CLASS=y
CONFIG_CDC_ACM_SERIAL_INITIALIZE_AT_BOOT=n
CONFIG_USBD_AUDIO2_CLASS=y
CONFIG_USBD_UAC2_FS_WINDOWS_WORKAROUND=y
CONFIG_HWINFO=y
CONFIG_USBD_LOG_LEVEL_WRN=y
CONFIG_UDC_DRIVER_LOG_LEVEL_WRN=y
CONFIG_USBD_MAX_UDC_MSG=64
CONFIG_USBD_THREAD_STACK_SIZE=2048
CONFIG_UDC_BUF_COUNT=32
CONFIG_UDC_BUF_POOL_SIZE=4096
CONFIG_UDC_RPI_PICO_STACK_SIZE=2048
